# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
labname: 계산신경과학연구실
labname_short: ChungLab
email: physi5logy@gmail.com
logo: SNU_BL.png
description: > # this means to ignore newlines until "baseurl:"
  ChungLab of Computational Neuroscience, Seoul National University; 서울대학교 치과대학 정지훈 교수 감각신경 연구실; Gehoon Chung;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  ChungLab
google-site-verification:

# Build settings
markdown: kramdown
include: ['_pages']
plugins:
  - jekyll-seo-tag
